version: '3.3'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
      - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot
    environment:
      - TZ=Europe/Moscow
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    networks:
      - tg_bot
    ports:
      - "27017:27017"
    environment:
      - TZ=Europe/Moscow
  redis:
    image: redis
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis
      - ./data/redis:/usr/local/etc/redis/redis.conf
    networks:
      - tg_bot
    environment:
      - TZ=Europe/Moscow



networks:
  tg_bot:
    driver: bridge


