buttons:
  back: ⬅️ Назад
  ban: Забанить
texts:
  admin: |
    ✌️<b>Админские функции</b>
    ➖➖➖➖➖➖➖➖➖
    /stats - 📊 статистика по пользователям бота
    /users - 📁выгрузить список пользователей
    /mailings - 📱 список всех рассылок
    /add_mailing - добавить рассылку
    
    /channels - 📁список каналов в обязательной подписке
    /add_sub - 👩‍💻 добавить в обязательную подписку
    /del_sub - 👩‍💻 удалить из обязательной подписки

    /refs - список реферальных ссылок
    /ref_stats - статистика реферальной ссылки
    /add_ref - добавить реферальную ссылку
    /del_ref - удалить реферальную ссылку

    /ban - забанить пользователя
    /unban - разбанить пользователя

  admin_texts:
    add_channel__id: 'Перешлите сюда id канала, который хотите добавить'
    add_channel__id_uncorrected: 'Id канала должно быть числом, проверьте сообщение и попробуйте еще раз: /add_sub'
    add_channel__link: 'Скиньте ссылку на канал, по которой будут переходить пользователи'
    add_channel__success: 'Канал добавлен'

    get_channels__one: |
      {}) <code>{}</code> - <a href='{}'>перейти к каналу</a>
    get_channels__not: 'Каналов нет, воспользуйтесь /add_sub, чтобы добавить новый канал'

    del_channel__link: 'Скиньте ссылку канала, который хотите удалить'
    del_channel__success: 'Канал удален'
    del_channel__not_found: |
      Такого канала нет в ОП.
      Используйте /channels, чтобы посмотреть все каналы'

    add_ref__date: 'Введите дату в формате день.месяц.год (Пример: 20.11.2022)'
    add_ref__date_uncorrected: 'Неверно заданная дата, попробуйте еще раз: /add_ref'
    add_ref__price: 'Введите число - цену реферальной ссылки (в рублях)'
    add_ref__price_uncorrected: 'В цене должны присутствовать только цифры, попробуйте еще раз: /add_ref'
    add_ref__contact: 'Введите контакт (пример: @anyone)'
    add_ref__success: 'Реферальная ссылка добавлена: <code>{}</code>'

    del_ref__link: 'Скиньте реферальную ссылку, который хотите удалить'
    del_ref__success: 'Реферальная ссылка удалена'
    del_ref__not_found: 'Реферальная ссылка удалена'

    get_refs__not_found: 'Реферальных ссылок нет, воспользуйтесь /add_ref, чтобы добавить новую'
    get_refs__one: |
      {}) <code>{}</code>
      <b>Дата:</b>{}
      <b>Цена:</b> {} руб
      <b>Контакт:</b> {}
      <b>Цена перехода:</b> {}

    get_stats_ref__link: 'Скиньте реферальную ссылку, статистику которой хотите получить'
    get_stats_ref__not_found: 'Такой ссылки не существует'

    add_mailing__post: 'Скиньте сюда пост, который хотите всем разослать'
    add_mailing__time: |
      Введите время в формате: <b>часы:минуты день.месяц.год</b>
      Пример: 18:01 08.11.2022
      
      Либо введите
      "сейчас" или "now" , чтобы рассылка началась прямо сейчас

    add_mailing__time_uncorrected: |
      Неверно заданное время.
      Введите время в формате: 
      <b>часы:минуты день.месяц.год</b>
      Либо введите "сейчас"/"now" , чтобы рассылка началась прямо сейчас


    del_mailing__success: 'Рассылка удалена'

    mailing__start: 'Рассылка началась'
    mailing__queue: 'Рассылка в очереди'
    mailing_finished: |
      <b>📱 Рассылка окончена!</b>
      <b>{0}</b>/<b>{1}</b>
      <b>Отправлено: </b> {2}
      <b>Не отправлено: </b> {3}
   



    get_mailing__plan: |
      Рассылка запланирована через {} часов {} минут!

    get_mailing__in_process: |
      Рассылка в процессе. 
      Отправлено: {}, не отправлено: {}

    get_mailings_not: 'Рассылок нет, воспользуйтесь /add_mailing, чтобы ее добавить'

    ban_user__id: 'Введите id пользователя, которого хотите забанить'
    ban_user__id_uncorrected: 'Id должен быть числом, попробуйте еще раз: /ban'
    ban_user__success: 'Пользователь забанен'

    unban_user__id: 'Введите id пользователя, которого хотите разбанить'
    unban_user__id_uncorrected: 'Id должен быть числом, попробуйте еще раз: /unban'
    unban_user__success: 'Пользователь разбанен'

    stats: |
      📊 Статистика бота
      <b>Всего пользователей:</b> {}
      <b>Всего Задоначено:</b> {}
    

    link_stats: |
      <b>– Статистика</b>
      👤 Новых юзеров: {}
      Всего переходов: {}
      
      <b>– Че по деньгам?</b>
      💵 Цена: {}
      🪙 Цена перехода: {}
      💰 Цена нового пользователя: {}
      
      🤑 Донатеров: {}
      💰 Задонатили: {}



  correct_captcha: |
    <b>👮Кажется ты не робот</b>
    <i>Извиняемся, не признали</i>'
  enter_captcha: |
    <b>⚠️ Замечена подозрительная активность </b>
    Пользователи с /vip никогда получают это сообщение.
    <b><i>✍️ Пожалуйста введите каптчу чтобы продолжить:</i></b>'

  not_correct_captcha: ❌
  not_understand: |
    <b>Я не понимаю тебя ☹️
    
    </b>Для использования бота пользуйся кнопками снизу или меню команд
  sponsor: |
    <b>✋ Чтобы продолжить пользоваться ботом, вы должны подписаться на наши
    каналы</b>
  sponsor__success: 'Спасибо, Вы подписались на все каналы! Продолжайте пользоваться ботом'
  sponsor__not: 'Вы не подписались на все каналы!'
  start_text: |
    😘 ПРИВЕТ
    Это стартовый текст для пользователя - start_text в config.yaml
  unbanned: |
    <b>🕊 Вы разблокированы в боте!</b>
    <i>Пожалуйста, ведите себя хорошо 👌</i>'
  user_banned: Забанен 🚫
  you_are_banned: |
    <b>⛔️ Вы заблокированы за подозрительную активность по многочисленным
    жалобам пользователей бота</b>
  you_are_banned_time: |
    <b>⛔️ Вы заблокированы на {0} час {1} минут за подозрительную
    активность по многочисленным жалобам пользователей бота</b>
prices:
  1:
    days: !!int 1
    price: !!int 79
    discount: !!int 49
    button: 24 часа - {0} ₽
    description: vip_1_day
  7:
    days: !!int 7
    price: !!int 149
    discount: !!int 99
    button: 7 дней - {0} ₽
    description: vip_7_day
  30:
    days: !!int 30
    price: !!int 179
    discount: !!int 129
    button: Месяц - {0} ₽
    description: vip_30_day
  forever:
    days: forever
    price: !!int 499
    discount: !!int 299
    button: Навсегда - {0} ₽
    description: vip_forever
  reset_react:
    price: !!int 19
    description: reset_react
  unban:
    price: !!int 79
    description: unban